module.exports = [
   {
      customer: 'Company A',
      start: 'Company B',
      destination: 'Company Z',
      placeLoad: 'Recanati, via ugo foscolo 4',
      placeUnload: 'Ancona, piazza del popolo',
      dateLoad: '2016-05-23',
      dateUnload: '2016-05-25',
      weight: 30,
      cost: 2000,
   }, {
      customer: 'Company B',
      start: 'Company B',
      destination: 'Company Z',
      placeLoad: 'Montecassiano, via ugo foscolo 4',
      placeUnload: 'Macerata, via ugo foscolo 4',
      dateLoad: '07/02/2016',
      dateUnload: '04/02/2016',
      weight: 510,
      cost: 300,
   },{
      customer: 'Company H',
      start: 'Company B',
      destination: 'Company R',
      placeLoad: 'Montecassiano, via ugo foscolo 4',
      placeUnload: 'Macerata, via ugo foscolo 4',
      dateLoad: '07/02/2016',
      dateUnload: '04/02/2016',
      weight: 150,
      cost: 800,
   },{
      customer: 'Company Q',
      start: 'Company J',
      destination: 'Company Z',
      placeLoad: 'Montecassiano, via ugo foscolo 4',
      placeUnload: 'Macerata, via ugo foscolo 4',
      dateLoad: '07/02/2016',
      dateUnload: '04/02/2016',
      weight: 250,
      cost: 700,
   },{
      customer: 'Company X',
      start: 'Company D',
      destination: 'Company O',
      placeLoad: 'Montecassiano, via ugo foscolo 4',
      placeUnload: 'Macerata, via ugo foscolo 4',
      dateLoad: '07/02/2016',
      dateUnload: '04/02/2016',
      weight: 10,
      cost: 5000,
   }
];